pluginManagement {
    repositories {
		gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net'
        }
        gradlePluginPortal()
    }
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'OkZoomer'

include('mod_common', 'mod_fabric') //, 'mod_norge') // FIXME re-enable neoforge once 1.21.9 releases
