[versions]
minecraft = "1.21.5-pre3"
parchment = "2025.02.16"

fabric_loom = "1.10.4"
fabric_loader = "0.16.10"
moddevgradle = "2.0.78"
neoforge = "21.4.111-beta"

fabric_api = "0.119.1+1.21.5"
wrench_wrapper = "0.6.2"

modmenu = "14.0.0-beta.2"
accessories = "1.2.18-beta+1.21.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.4", version.ref = "parchment" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
wrench_wrapper = { module = "io.github.ennuil:wrench_wrapper", version.ref = "wrench_wrapper" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

accessories_fabric = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }
accessories_norge = { module = "io.wispforest:accessories-neoforge", version.ref = "accessories" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
