[versions]
minecraft = "26.2-rc-1"

shadow = "9.4.2"
mod_publish_plugin = "1.1.0"

fabric_loom = "1.17.11"
fabric_loader = "0.19.3"
moddevgradle = "2.0.141"
neoforge = "26.2.0-alpha.0+rc-1.20260611.132638"

fabric_api = "0.150.3+26.2"
wrench_wrapper = "0.8.1"

modmenu = "20.0.0-alpha.1"
sodium = "0.8.12+mc26.1.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
wrench_wrapper_api_fabric = { module = "page.langeweile.wrench_wrapper:api_fabric", version.ref = "wrench_wrapper" }
wrench_wrapper_api_neoforge = { module = "page.langeweile.wrench_wrapper:api_neoforge", version.ref = "wrench_wrapper" }
wrench_wrapper_impl = { module = "page.langeweile.wrench_wrapper:impl", version.ref = "wrench_wrapper" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
sodium_fabric = { module = "net.caffeinemc:sodium-fabric-api", version.ref = "sodium" }
sodium_neoforge = { module = "net.caffeinemc:sodium-neoforge-api", version.ref = "sodium" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
wrench_wrapper_fabric = ["wrench_wrapper_api_fabric", "wrench_wrapper_impl"]
wrench_wrapper_neoforge = ["wrench_wrapper_api_neoforge", "wrench_wrapper_impl"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
mod_publish_plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod_publish_plugin" }
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
