plugins {
	id 'mod_conventions_loader'
	alias libs.plugins.fabric.loom.remap
}

repositories {
	maven { url = 'https://maven.terraformersmc.com/releases' }
}

base.archivesName = 'ok_zoomer-fabric'

// All the dependencies are declared at gradle/libs.version.toml and referenced with "libs.<id>"
// See https://docs.gradle.org/current/userguide/platforms.html for information on how version catalogs work.
dependencies {
	minecraft libs.minecraft
	mappings loom.officialMojangMappings()
	modImplementation libs.fabric.loader

	modImplementation libs.fabric.api

	modCompileOnly libs.modmenu
	modLocalRuntime libs.modmenu

	modImplementation libs.wrench.wrapper.api.fabric

	include libs.bundles.wrench.wrapper.fabric
}

loom {
	def atFile = project(':mod_common').file("src/main/resources/${mod_id}.accesswidener")
	if (atFile.exists()) {
		accessWidenerPath.set(atFile)
	}

	runs {
		named('client') {
			client()
			configName = 'Fabric Client'
			ideConfigGenerated(true)
			runDir('run')
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}
