name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: 25
  TAG: ${{ github.ref_name }}
  BUILD_NUMBER: ${{ github.run_number }}
  MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
  MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
  MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
  GITHUB_TOKEN: ${{ github.token }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v6
        with:
          distribution: 'microsoft'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build

      - name: Maven Release
        if: ${{ env.MAVEN_UPLOAD_URL }}
        run: ./gradlew publish

      - name: Publish on GitHub, Modrinth and CurseForge
        run: ./gradlew publishMods

      - name: Notify Discord
        uses: Up-Mods/action-discord-release@main
        with:
          version: ${{ github.ref_name }}
          webhook-url: ${{ secrets.ANNOUNCEMENT_WEBHOOK_URL }}
          curseforge-project-id: "1465234"
          modrinth-project-id: "4lDrPSXX"
          thumbnail-url: https://mod-assets.upcraft.dev/promo/ok-zoomer/icon_128x.png
